version: '3'
services:
  database:
    container_name: database
    image: mariadb:latest
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - ./data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    restart: on-failure
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_PASSWORD: ${DB_USER_PW}
      MARIADB_USER: ${DB_USER}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PW}
  bookshelf-api:
    build: ./bookshelf/app
    container_name: bookshelf-api
    ports: 
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on: 
      - database
    restart: on-failure      
networks:
  default:
volumes:
  data:
    driver: local
